apiVersion: v1
kind: LimitRange
metadata:
  name: ephemeralstoragelimits
spec:
  limits:
   - type: Container
     max:
       ephemeral-storage: 2Gi
     default:
       ephemeral-storage: 1Gi
     defaultRequest:
       ephemeral-storage: 100Mi 
